SELECT P.PID ,P.NAME , B.BEDID , B.RENT ,B.WARDID FROM PATIENT P, BED B , PATIENTBED PB WHERE 
P.PID = PB.PID AND B.BEDID = PB.BEDID AND B.BEDTYPE = 'NOT AVAILABLE';


SELECT P.PID ,P.NAME , B.BEDID , B.RENT ,B.WARDID FROM PATIENT P, BED B , PATIENTBED PB WHERE 
P.PID = PB.PID AND B.BEDID = PB.BEDID ;AND B.BEDTYPE = 'AVAILABLE';

SELECT DISTINCT P.PID, P.NAME FROM DOCTOR D , PATIENT P , PDHISTORY PD 
WHERE D.DID = PD.DID AND P.PID = PD.PID AND D.DID='D001' AND P.NAME LIKE '% P%' 
OR P.NAME LIKE 'P%'
ORDER BY PID;

SELECT * FROM EMP WHERE EID ='E001';