CREATE OR REPLACE PROCEDURE ADDAPPOINT(PID1 CHAR, DID1 CHAR, DATE1 DATE) AS
	NUM NUMBER;
	EXISTING NUMBER;
	BEGIN
		EXISTING := 0;
		NUM := 0;
		SELECT COUNT(*) INTO NUM FROM PDAPPOINT WHERE DID=DID1 AND DATE1=APPOINTDATE;
		SELECT COUNT(*) INTO EXISTING FROM PDAPPOINT WHERE DID=DID1 AND PID1=PID AND DATE1=APPOINTDATE;
		IF NUM>=2 THEN
			DBMS_OUTPUT.PUT_LINE('TOO MANY APPOINTMENTS');
		ELSIF EXISTING>0 THEN
			DBMS_OUTPUT.PUT_LINE('YOU ALREADY HAVE AN APPOINTMENT WITH DOCTOR '||DID1|| ' ON '||DATE1);
		ELSE
			INSERT INTO PDAPPOINT VALUES(PID1, DID1, DATE1);
		END IF;
	END;
/ 

CREATE OR REPLACE PROCEDURE INSERT_DOCTOR(NAME1 VARCHAR2) AS
	MAXID CHAR(4);
	ID CHAR(4);
	DNAME VARCHAR2(20);
	NUM NUMBER;
	BEGIN
		SELECT DID INTO MAXID FROM DOCTOR 
		WHERE TO_NUMBER(SUBSTR(DID, 2)) >= ALL(SELECT TO_NUMBER(SUBSTR(DID, 2)) FROM DOCTOR);
		SELECT TO_NUMBER(SUBSTR(DID, 2)) INTO NUM FROM DOCTOR WHERE DID=MAXID;
		NUM := NUM+1;
		IF NUM<10 THEN
			ID := 'D00'||TO_CHAR(NUM);
		ELSIF NUM<100 THEN
			ID := 'D0'||TO_CHAR(NUM);
		ELSE
			ID := 'D'||TO_CHAR(NUM);
		END IF;
		INSERT INTO DOCTOR(DID, NAME) VALUES(ID, NAME1);
	END;
/

EXECUTE INSERT_DOCTOR('JALIL');
SELECT * FROM DOCTOR;




CREATE OR REPLACE PROCEDURE INSERT_NURSE(NAME1 VARCHAR2) AS
	MAXID CHAR(4);
	ID CHAR(4);
	NNAME VARCHAR2(20);
	NUM NUMBER;
	BEGIN
		SELECT NID INTO MAXID FROM NURSE 
		WHERE TO_NUMBER(SUBSTR(NID, 2)) >= ALL(SELECT TO_NUMBER(SUBSTR(NID, 2)) FROM NURSE);
		SELECT TO_NUMBER(SUBSTR(NID, 2)) INTO NUM FROM NURSE WHERE NID=MAXID;
		NUM := NUM+1;
		IF NUM<10 THEN
			ID := 'N00'||TO_CHAR(NUM);
		ELSIF NUM<100 THEN
			ID := 'N0'||TO_CHAR(NUM);
		ELSE
			ID := 'N'||TO_CHAR(NUM);
		END IF;
		INSERT INTO NURSE(NID, NAME) VALUES(ID, NAME1);
	END;
/

EXECUTE INSERT_NURSE('FATIMA');
SELECT * FROM NURSE;
